# Generated by Django 3.2.2 on 2021-06-08 12:27

import Post_Management.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post_Management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.ImageField(blank=True, default='posts/default.jpg', upload_to=Post_Management.models.upload_to),
        ),
        migrations.AlterField(
            model_name='content',
            name='uploaded_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 8, 17, 57, 58, 216406)),
        ),
    ]
