# Generated by Django 3.2.2 on 2021-06-08 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post_Management', '0002_auto_20210608_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='uploaded_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 8, 18, 53, 29, 673649)),
        ),
    ]
