# Generated by Django 3.2.2 on 2021-05-28 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_status', models.CharField(default='Waiting', max_length=15)),
                ('entity1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity1', to='Profile.profilemodel')),
                ('entity2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity2', to='Profile.profilemodel')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='Profile.profilemodel')),
            ],
        ),
    ]
