# Generated by Django 3.2.2 on 2021-06-17 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recommendation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestion',
            old_name='id',
            new_name='suggestionId',
        ),
    ]
