# Generated by Django 3.2.2 on 2021-06-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_auto_20210618_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='educationFieldString',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
