# Generated by Django 3.2.2 on 2021-07-05 09:49

import Profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0009_rename_workposition_profilemodel_workpositionstring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pics/default.jpg', upload_to=Profile.models.upload_to),
        ),
    ]
