# Generated by Django 3.2.2 on 2021-07-06 10:55

import Profile.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0010_alter_profilemodel_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='profile_pic',
        ),
        migrations.CreateModel(
            name='ProfilePicModel',
            fields=[
                ('pic_id', models.AutoField(primary_key=True, serialize=False)),
                ('profile_pic', models.ImageField(blank=True, default='profile_pics/default.jpg', upload_to=Profile.models.upload_to)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_profile_pic', to='Profile.profilemodel')),
            ],
        ),
    ]
