# Generated by Django 3.2.2 on 2021-07-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0011_auto_20210706_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='dateofbirth',
            field=models.CharField(default='1/1/1900', max_length=20),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='graduationYear',
            field=models.CharField(default='1900', max_length=10),
        ),
    ]
