# Generated by Django 3.2.2 on 2021-07-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0013_remove_profilemodel_dateofbirth'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='dateofbirth',
            field=models.CharField(default='1/1/1900', max_length=20),
        ),
    ]
